
_target_: model.GoogleUSMAdapter

n_adaptive_layers: 12
encoder_id: "Atotti/google-usm"
model_id: "google/gemma-3n-e2b-it"
adapter_config:
  "dim_in": 1536
  "dim_bottleneck": 1024
  "init_option": "bert"
  "adapter_scalar": 1.0
  "pre_ln_class": "Gemma3nRMSNorm"
