defaults:
  - model: feature_cleaner/google-usm
  - data: deg_gemma_24khz_30sec
  - optimizer: feature_cleaner
  - trainer: default
  - _self_

# no hydra logging
hydra:
  output_subdir: null
  run:
    dir: .
  # multirun
  sweep:
    dir: .