defaults:
  - model: feature_cleaner/google-usm
  - data: deg_gemma_16khz_30sec
  - optimizer: default
  - trainer: default
  - _self_

# no hydra logging
hydra:
  output_subdir: null
  run:
    dir: .
  # multirun
  sweep:
    dir: .