defaults:
  - model: cleaner_google-usm
  - data: 16khz_30sec
  - optimizer: default
  - trainer: default
  - _self_

# no hydra logging
hydra:
  output_subdir: null
  run:
    dir: .
  # multirun
  sweep:
    dir: .